/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Compress: () => import('#controllers/compress_controller'),
  Merge: () => import('#controllers/merge_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Organize: () => import('#controllers/organize_controller'),
  PdfToJpg: () => import('#controllers/pdf_to_jpg_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Split: () => import('#controllers/split_controller'),
  JpgToPdf: () => import('#controllers/jpg_to_pdf_controller'),
}
